version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "reicigo"
    ports:
      - "3306:3306"

  doris:
   image: apache/doris:doris-all-in-one-2.1.0
   ports:
     - "8030:8030"
     - "8040:8040"
     - "9030:9030"
