source:
  type: mysql
  hostname: localhost
  port: 3306
  username: root
  password: ""
  tables: reicigo.\.*
  server-id: 5400-5500
  server-time-zone: UTC

sink:
  type: doris
  name: Doris Sink
  fenodes: 127.0.0.1:8030
  username: root
  password: ""
  table.create.properties.light_schema_change: true
  table.create.properties.replication_num: 1

pipeline:
  name: Sync MySQL Database to Doris
  parallelism: 4

route:
  - source-table: reicigo.\.*
    sink-table: reicigo.terminus
    description: "route all sharded tables to terminus"

transform:
  - source-table: reicigo.\.*
    projection: ID, UPPER(ID) AS UPID, LOLO, UPPER(LOLO) AS UPLOLO
    filter: CHAR_LENGTH(ID) > 5
    description: project fields from source table